; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

build_unflags =
    -fpermissive
    -std=gnu++11
    -std=gnu++14
    -std=gnu++17
    -O0
    -O1
    -O2
    -O3
    -Os
    -Oz
    
build_flags =
    -std=gnu++20
    -Wall
    -Wno-ignored-qualifiers
    -Wno-unused-parameter
    -Wno-maybe-musttail-local-addr

    ; arduino causes a lot of these
    -Wno-volatile

    -Wno-format

    -Ofast
    -fno-strict-aliasing
    -funroll-loops
    -DUSB_DUAL_SERIAL

    ; also don't use these on arduino
    ; -Wpedantic
    ; -Wextra
lib_deps = 
    SdFat ; Arduino's SD is too slow, and doesn't support many features
    https://github.com/pavel-kirienko/o1heap

; use teensy cli instead of teensy gui
upload_protocol = teensy-cli

[env:native]
platform = native

build_flags =
    -fno-exceptions ; mimic Arduino's behavior
    -fno-rtti ; mimic Arduino's behavior
    -g
    -O0
    -fsanitize=address
    -fsanitize=undefined
    -std=gnu++20
    -Wall
    -Wextra
    -Wpedantic
    -Wno-ignored-qualifiers
    -Wno-unused-parameter
    -Wno-maybe-musttail-local-addr

[env:teensy41_release]
extends = env:teensy41
build_type = release
build_flags =
    ${env:teensy41.build_flags}
    -DNDEBUG

[env:native_release]
platform = native
build_flags =
    -fno-exceptions ; mimic Arduino's behavior
    -fno-rtti ; mimic Arduino's behavior
    -Ofast
    -march=native
    -funroll-loops
    -std=gnu++20
    -DNDEBUG
    -DNTRACE
    -Wall
    -Wextra
    -Wpedantic
    -Werror
    -Wno-ignored-qualifiers
    -Wno-unused-parameter
    -Wno-maybe-musttail-local-addr
